export enum CATEGORY_DOCS_ENUM {
  PROJECT = 'PROJECT',
  COMPANY = 'COMPANY',
}

export enum PRIVACY_DOCS_ENUM {
  PUBLIC = 'PUBLIC',
  INDIVIDUAL_INVESTING = 'INDIVIDUAL_INVESTING',
  INSTITUTIONAL_INVESTING = 'INSTITUTIONAL_INVESTING',
  ALREADY_INVESTED = 'ALREADY_INVESTED',
}
