export enum OrganizationEnum {
  STATE = '1',
  COOPERATION = '2',
  COMPANY = 'COMPANY', // LOCAL + INTERNATIONAL
  OTHER = '5',

  // LOCAL = '3',
  // INTERNATIONAL = '4',
}

export enum PUBLISHER_TYPE_ENUM {
  STATE = 'STATE',
  COOPERATION = 'COOPERATION',
  COMPANY = 'COMPANY', // LOCAL + INTERNATIONAL
  OTHER = 'OTHER',
}

export enum PUBLISHER_POST_TYPE_ENUM {
  SYSTEM = 'SYSTEM',
  EXTERNAL = 'EXTERNAL',
  BOTH = 'BOTH',
}
