export enum CAMPAIGN_TYPE_ENUMS {
  PERSONAL = 'PERSONAL',
  ORGANIZATION = 'ORGANIZATION',
}

export enum CAMPAIGN_CATEGORY_ENUMS {
  EQUITY = 'EQUITY',
  REWARD = 'REWARD',
  SPONSOR = 'SPONSOR',
  BIDING = 'BIDING',
  MA = 'M&A',
  TRANSFER = 'TRANSFER',
}
